version: '2'
services:
  base:
     build:
       context: .
       dockerfile: config/Dockerfile
     working_dir: /var/lib/eventkit
     user: eventkit
     environment:
        - DATABASE_URL=postgres://eventkit:eventkit_exports@postgis:5432/eventkit_exports
        - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
        - DEBUG=True
        - PRODUCTION=True
        - EXPORT_DOWNLOAD_ROOT=/var/lib/eventkit/exports_download
        - SITE_NAME=${SITE_NAME}
        - PYTHONWARNINGS=ignore
     extra_hosts:
        - "${SITE_NAME}:${SITE_IP}"
     command: echo 'Base box is not used, exiting now'
  eventkit:
      extends:
        service: base
      depends_on:
        - postgis
        - rabbitmq
      links:
        - postgis
        - rabbitmq
      expose:
        - "6080"
      command: sh /var/lib/eventkit/scripts/eventkit-entrypoint.sh
  celery:
      extends:
        service: base
      depends_on:
        - postgis
        - rabbitmq
        - eventkit
      links:
        - postgis
        - rabbitmq
      environment:
        - LOGLEVEL=error
        - CONCURRENCY=1
      command: sh /var/lib/eventkit/scripts/celery-entrypoint.sh
  postgis:
    image: mdillon/postgis:9.5
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    expose:
      - "5432"
  rabbitmq:
     image: rabbitmq:3.6.5
     expose:
       - "5672"
  httpd:
     build:
       context: .
       dockerfile: config/Dockerfile_httpd
     volumes:
       - /home/mvv/Downloads/celerykey2:/opt/celery.pem
       - ./eventkit_cloud:/var/lib/eventkit/eventkit_cloud
       - ./exports_download:/var/lib/eventkit/exports_download
     image: httpd:2.4.23
     ports:
        - "80:80"
