version: '2'
services:
  base:
     volumes:
       - ./:/var/lib/eventkit/
     build:
       context: .
       dockerfile: config/Dockerfile
     working_dir: /var/lib/eventkit
     user: eventkit
     environment:
        - DATABASE_URL=postgis://eventkit:eventkit_exports@postgis:5432/eventkit_exports
        - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
        - DEBUG=True
        - PRODUCTION=True
        - DJANGO_LOG_LEVEL=ERROR
        - LOG_LEVEL=ERROR
        - EXPORT_DOWNLOAD_ROOT=/var/lib/eventkit/exports_download
        - SITE_NAME=${SITE_NAME}
     extra_hosts:
        - "${SITE_NAME}:${SITE_IP}"
     command: echo 'Base box is not used, exiting now'
  eventkit:
      extends:
        service: base
      depends_on:
        - postgis
        - rabbitmq
      links:
        - postgis
        - rabbitmq
      expose:
        - "6080"
      command: sh /var/lib/eventkit/scripts/eventkit-entrypoint.sh
  celery:
      extends:
        service: base
      depends_on:
        - postgis
        - rabbitmq
        - eventkit
      links:
        - postgis
        - rabbitmq
      environment:
        # Concurrency needs to be greater than 1 to support Task Cancellation.
        - CONCURRENCY=2
      command: sh /var/lib/eventkit/scripts/celery-entrypoint.sh
  celery-beat:
      extends:
        service: base
      depends_on:
        - postgis
        - rabbitmq
        - celery
        - eventkit
      links:
        - postgis
        - rabbitmq
      environment:
        - LOGLEVEL=ERROR
        - CONCURRENCY=1
      command: sh /var/lib/eventkit/scripts/celery-beat-entrypoint.sh
  postgis:
    image: mdillon/postgis:9.5
    environment:
      - POSTGRES_USER=eventkit
      - POSTGRES_PASSWORD=eventkit_exports
      - POSTGRES_DB=eventkit_exports
    expose:
      - "5432"
  rabbitmq:
       image: rabbitmq:3.6.6-management
  httpd:
       build:
         context: .
         dockerfile: config/Dockerfile_httpd
       volumes:
         - ./eventkit_cloud:/var/lib/eventkit/eventkit_cloud
         - ./exports_download:/var/lib/eventkit/exports_download
       image: httpd:2.4.23
       ports:
          - "80:80"
#  flower:
#       extends:
#          service: base
#       depends_on:
#          - rabbitmq
#       links:
#          - rabbitmq
#       ports:
#         - "49555:5555"
#       command: sh /var/lib/eventkit/scripts/flower-entrypoint.sh
#       extra_hosts:
#        - "cloud.eventkit.dev:192.168.99.130"

