version: '2'
services:
  base:
     volumes:
       - ./:/var/lib/eventkit/
     build:
       context: .
       dockerfile: config/Dockerfile
     working_dir: /var/lib/eventkit
     user: eventkit
     environment:
        - DATABASE_URL=postgres://eventkit:eventkit_exports@postgis:5432/eventkit_exports
        - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
        - DEBUG=True
        - PRODUCTION=True
        - DJANGO_LOG_LEVEL=ERROR
        - LOG_LEVEL=INFO
        - EXPORT_DOWNLOAD_ROOT=/var/lib/eventkit/exports_download
        - SITE_NAME
        - PYTHONWARNINGS=ignore
     extra_hosts:
        - "${SITE_NAME}:${SITE_IP}"
     command: echo 'Base box is not used, exiting now'
  eventkit:
      extends:
        service: base
      depends_on:
        - postgis
        - rabbitmq
      links:
        - postgis
        - rabbitmq
      expose:
        - "6080"
      command: sh /var/lib/eventkit/scripts/eventkit-entrypoint.sh
  celery:
      extends:
        service: base
      depends_on:
        - postgis
        - rabbitmq
        - eventkit
      links:
        - postgis
        - rabbitmq
      environment:
        - CONCURRENCY=1
        - MAPPROXY_CONCURRENCY=1
      command: sh /var/lib/eventkit/scripts/celery-entrypoint.sh
      volumes:
       - ${EC2_PEM}:/opt/celery.pem
  celery-beat:
      extends:
        service: base
      depends_on:
        - postgis
        - rabbitmq
        - celery
        - eventkit
      links:
        - postgis
        - rabbitmq
      environment:
        - CONCURRENCY=1
      command: sh /var/lib/eventkit/scripts/celery-beat-entrypoint.sh
  postgis:
    image: mdillon/postgis:9.5
    environment:
      - POSTGRES_USER=eventkit
      - POSTGRES_PASSWORD=eventkit_exports
      - POSTGRES_DB=eventkit_exports
    expose:
      - "5432"
    # This is stored up a directory because there will be permissions issues if ran with Vagrant shared directory.
    volumes:
      - "../eventkit_database/database:/var/lib/postgresql/data"
  rabbitmq:
       image: rabbitmq:3.6.6-management
       expose:
        - "5672"
  httpd:
       build:
         context: .
         dockerfile: config/Dockerfile_httpd
       depends_on:
        - eventkit
       links:
        - eventkit
       volumes:
         - ./eventkit_cloud:/var/lib/eventkit/eventkit_cloud
         - ./exports_download:/var/lib/eventkit/exports_download
       image: httpd:2.4.23
       ports:
          - "80:80"
  flower:
       extends:
          service: base
       depends_on:
          - rabbitmq
       links:
          - rabbitmq
       ports:
         - "49555:5555"
       command: sh /var/lib/eventkit/scripts/flower-entrypoint.sh
       extra_hosts:
         - "${SITE_NAME}:${SITE_IP}"
       environment:
         - BROKER_API=http://guest:guest@rabbitmq:15672/api/
         - BROKER_URL=amqp://guest:guest@rabbitmq:5672/

